# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod
mod_version=0.1.12b
mod_id=vampiresdelight
mod_name=VampiresDelight
mod_display_name=Vampire's Delight
mod_license=MIT

# NeoForge
neo_version=21.1.219
neo_version_range=[21.1.57,)
loader_version_range=[4,)

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)

# Mappings
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Main Dependencies
vampirism_version=1.21-1.10.10
vampirism_version_range=[1.10.0,1.11.0)

farmers_delight_version=1.21.1-1.3.1
farmers_delight_version_range=[1.3.0,)

# Other Dependencies
appleskin_version=mc1.21-3.0.5
include_appleskin=true

jei_version=19.16.0.155

werewolves_version=1.21-2.0.3.1
include_werewolves=true