# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Mod
mod_version=0.1.13b
mod_id=vampiresdelight
mod_name=Vampire's Delight
mod_license=MIT
mod_group_id=net.grid.vampiresdelight
mod_authors=GridExpert
mod_description=A compatibility mod for Vampirism and Farmer's Delight with garlic aftertaste
mod_issue_tracker=https://github.com/TheGridExpert/VampiresDelight/issues
mod_update_url=https://api.modrinth.com/updates/vampires-delight/forge_updates.json

## Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

## Forge
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Farmer's Delight
farmers_delight_version=1.3.2
farmers_delight_version_range=[1.3.1,)

# Vampirism
vampirism_version=1.10.15
vampirism_version_range=[1.10.10,2.0)

# Werewolves
include_werewolves=true
include_werewolves_runtime=true
werewolves_version=2.0.2.7
werewolves_version_range=[2.0.2.7,)

# JEI
include_jei=true
jei_version=15.20.0.130

# AppleSkin
include_appleskin=true
appleskin_version=2.5.1
