# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=0.1.7c
mod_id=vampiresdelight
mod_name=VampiresDelight
mod_display_name=Vampire's Delight
credits=Cheaterpaul, Maxanier, Vectorwing, DimensionPainter, Cursed Shadow and many others
mod_license=MIT

# Forge
forge_version=47.1.0
forge_version_range=[47,)
loader_version_range=[47,)

# Minecraft
mc_version=1.20.1
mc_version_range=[1.20.1,)

# Mappings
mappings_channel=parchment
mappings_version=2023.09.03

# Main Dependencies
vampirism_version=1.10.9
vampirism_version_range=[1.10.7,)

farmersdelight_version=5051242
farmersdelight_version_range=[1.20.1-1.2.3,)

# Other Dependencies
appleskin_version = 2.5.1
include_appleskin = true

jei_version=15.3.0.4

werewolves_version = 5406832
include_werewolves = true