modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/TheGridExpert/VampiresDelight/issues"
license="${mod_license}"

[[mods]]
modId="vampiresdelight"
version="${mod_version}"
displayName="${mod_display_name}"
displayURL = "https://github.com/TheGridExpert/VampiresDelight"
logoFile="logo.png"
logoBlur=false
itemIcon = "vampiresdelight:dark_stone_stove"
configBackground = "vampiresdelight:textures/block/dark_stone_small_bricks.png"
credits='''\n
    - Cheaterpaul (Vampirism and code assistance)
    - Maxanier (Vampirism)
    - Vectorwing (Farmer's Delight)
    - Lunofe/Zin (code and balance)
Translators:
    - DimensionPainter (Russian)
    - Cursed Shadow (French)
    - stairs (Chinese)
'''
authors="GridExpert"
description='''
Makes Vampirism and Farmer's Delight more compatible
'''

[[dependencies.vampiresdelight]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="vampirism"
mandatory=true
versionRange="${vampirism_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="farmersdelight"
mandatory=true
versionRange="${farmersdelight_version_range}"
ordering="NONE"
side="BOTH"