@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.grid.vampiresdelight.common.crafting;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;